services:
  app:
    image: phone-market
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8337:8337"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/phone_market
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: phone_market
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
      - ./sql/intitial:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data: